language: python
python:
  - "3.6"
cache: pip

install: 
  - pip install coverage
  - pip install coveralls
  - pip install nosexcover
  - pip install -r requirements.txt 

# command to run tests
script: nosetests --with-xcoverage --cover-package=api.v1.models --cover-tests 

after_success: 
  - coverage report
  - coveralls